snowtricks_home:
    path:   /
    defaults: { _controller: SnowtricksPlatformBundle:Trick:index }

snowtricks_add:
    path:   /new-trick
    defaults: { _controller: SnowtricksPlatformBundle:Trick:add }

snowtricks_view:
    path:   /{slug}
    defaults: { _controller: SnowtricksPlatformBundle:Trick:show }
    requirements:
        slug: '.+'
