snowtricks_home:
    path:   /
    defaults: { _controller: SnowtricksPlatformBundle:Trick:index }

snowtricks_add:
    path:   /trick/add
    defaults: { _controller: SnowtricksPlatformBundle:Trick:add }

snowtricks_update:
    path: /trick/update/{slug}
    defaults: { _controller: SnowtricksPlatformBundle:Trick:update }
    requirements:
        slug: "[a-zA-Z0-9-]+"

snowtricks_delete:
    path: /trick/delete/{id}
    defaults: { _controller: SnowtricksPlatformBundle:Trick:delete }
    requirements:
        slug: \d+

snowtricks_view:
    path:   /tricks/{slug}
    defaults: 
      _controller: SnowtricksPlatformBundle:Trick:show
    requirements:
        slug: "[a-zA-Z0-9-]+"

snowtricks_image_remove:
    path:   /image/remove/{id}
    defaults: { _controller: SnowtricksPlatformBundle:Image:remove }
    requirements:
        id: \d+

snowtricks_register:
    path:   /user/register
    defaults: { _controller: SnowtricksPlatformBundle:User:register }

snowtricks_confirm_register:
    path:   /user/confirm-register/{userId}-{token}
    defaults: { _controller: SnowtricksPlatformBundle:User:confirmRegister }

snowtricks_login:
    path:   /login
    defaults: { _controller: SnowtricksPlatformBundle:User:login }

snowtricks_account:
    path:   /user/account
    defaults: { _controller: SnowtricksPlatformBundle:User:account }

snowtricks_addavatar:
    path:   /user/add-avatar
    defaults: { _controller: SnowtricksPlatformBundle:User:addAvatar }

snowtricks_resetpass:
    path:   /user/reset-password
    defaults: { _controller: SnowtricksPlatformBundle:User:resetPass }

snowtricks_confirm_resetpass:
    path:   /user/confirm-reset-password/{userId}-{token}
    defaults: { _controller: SnowtricksPlatformBundle:User:confirmResetPass }

snowtricks_logout:
    path:   /logout