services:
#    snowtricks_platform.example:
#        class: Snowtricks\PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    Snowtricks\PlatformBundle\DataFixtures\:
        resource: '../../DataFixtures'
        tags: ['doctrine.fixture.orm']