<?php

namespace Snowtricks\PlatformBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends \Doctrine\ORM\EntityRepository
{
    public function paginator($trickId, $page, $perPage)
    {       
        $query = $this->createQueryBuilder('m')
            ->join('m.trick', 't')
            ->where('t.id = :trickId')
            ->setParameter('trickId', $trickId)
            ->orderBy('m.messagePublished', 'DESC')
            ->getQuery();

        $query
            ->setFirstResult(($page-1) * $perPage)
            ->setMaxResults($perPage);

        return new Paginator($query);
    }
}
