<?php

namespace Snowtricks\PlatformBundle\Repository;

/**
 * TrickRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrickRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Count the number of tricks save in database
     */
    public function countTricks()
    {
        $query = $this->createQueryBuilder('t')
            ->select('COUNT(t)');

        return $query->getQuery()->getSingleScalarResult();
    }

    /**
     * Request for search form
     */
    public function search($trickName, $group)
    {
        $query = $this->createQueryBuilder('t');

        if (!empty($trickName)) {
            $query->andWhere('t.name LIKE :trickName')->setParameter('trickName', '%'.$trickName.'%');
        }

        if (!empty($group)) {
            $query->andWhere('t.trickgroup = :group')->setParameter('group', $group);
        }

        return $query->getQuery()->getResult();
    }
}
